# stages:
#     - build
#     # - release

# variables:
#     NAME: tivoli-blender-tools

# build:
#     stage: build
#     image: python:alpine
#     script:
#         - apk add zip

#         # update __init__.py bl_info version

#         - python download_libs.py nt
#         - zip -r $NAME-$CI_COMMIT_REF_NAME-windows.zip $NAME
#         - rm -rf $NAME/libs

#         - python download_libs.py posix
#         - zip -r $NAME-$CI_COMMIT_REF_NAME-linux.zip $NAME
#         - rm -rf $NAME/libs
#     artifacts:
#         expire_in: 1 day
#         paths:
#             - $NAME-$CI_COMMIT_REF_NAME-*.zip
# # release:
# #     stage: release
# #     image: registry.gitlab.com/gitlab-org/release-cli
# #     only:
# #         - /^[0-9]+?\.[0-9]+?\.[0-9]+?$/i
# #     script:
# #         - release-cli create
# #           --name "Tivoli Blender Tools $CI_COMMIT_TAG"
# #           --description "Version $CI_COMMIT_TAG"
# #           --tag-name $CI_COMMIT_TAG
# #           --ref $CI_COMMIT_SHA
